[BE]ブログ記事一覧取得機能
keita7777/teamsdev_16_1 pull request #56
Opened 2024-11-02 05:28 UTC by yoshida0522

close #50

## やったこと・変更内容（ビューの変更がある場合はスクショによる比較などがあるとわかりやすい ）

ミネギシさんと確認・情報共有のために作成しました。

![スクリーンショット (64)](https://github.com/user-attachments/assets/138078cf-de72-48dd-a8b1-68ec962820e3)

![スクリーンショット (65)](https://github.com/user-attachments/assets/3d1dbb61-8e5b-4852-bd69-96601eec8241)

- supabaseの初期化ファイルを作成（ファイル名：supabase.ts）
- next.config.mjsにコードを追加（supabaseから画像を取得するため）
- env.localファイルを作成
- ArticleDataにデータ取得のコードを追加、テストデータはコメントアウト
- ArticleListにuseEffectを追加

## レビュー観点（レビューをする際に見てほしい点など）

- supabaseの初期化ファイルの配置場所はどこがいいのか
- .env.localのコードの書き方
- データ取得ファイルはどこに配置したらいいか（使いまわしできる？？）

2024-11-02 07:32 UTC, keita7777 commented
### supabaseの初期化ファイル
- 配置場所はどこでも良い気がする
- 記述内容はヨシダさんのほうが良いかも

→シナガワさんに確認してもらう

### データ取得
- 前回のミーティングでAPIエンドポイントを作成するというお話がありました（私の認識が間違っていなければ、app/api以下にroute.tsを作成してGETやPOSTメソッドを記述、対象のコンポーネントでfetch）。
getAllDataがDummyData/ArticleData.ts内で記述されていますが、この記述をroute.tsに持ってきてArticleListでfetchするというやり方もあります。
ただしわざわざAPIエンドポイントを作成する必要もないという話も出ましたのでどう実装するか検討
- ArticleListがクライアントコンポーネントになっていますが、データを取得するだけなのでサーバーコンポーネントで実装するものアリかと思います。
- postsテーブルのuser_id、category_idは、それぞれusersテーブル、categoriesテーブルと紐づいているので、ユーザー名とカテゴリの取得もできるはずです（Supabaseのテーブル設定が間違ってなければ、、、）

2024-11-04 15:00 UTC, yoshida0522 commented
ご指摘箇所修正致しました。
これでいいのか自信がないので、他に修正箇所等あれば仰ってください。
また、`ArticleList`はクライアントコンポーネントになっております。
サーバーサイドで何度も試しましたがなかんか上手くいきませんでした。
現在もサーバーサイドに修正中。

2024-11-05 02:55 UTC, keita7777 commented
・APIエンドポイントの統一
現在以下のようなディレクトリ構造になっています。GETとPOSTは同じファイルに記述してよいと思うのでどちらかに統一させたいです。blogにするのはいかがでしょうか?（名称なのでどちらでも良いのですが、、、）
ヨシダさん：app/api/getData/route.ts
ミネギシ：app/api/blog/route.ts

・現状「user_id」「category_id」が画面上に表示されていますが、ユーザー名とカテゴリ名を表示させたいところですね

・日付の表示形式を「XXXX/XX/XX」「XXXX年XX月XX日」とかにすると綺麗かと思います

2024-11-08 10:37 UTC, shtk0llq reviewed
レビューいたしました。
全体的によく書かれています。

supabase.ts の配置箇所ですが、外部のライブラリや便利な関数などは、libs もしくは utils ディレクトリに配置することが一般的です。
また、supabase.tsの初期化についてですが、今回は typescript を使用していることや next.js を使用していることもあるのでミネギシさんが書かれている初期化を使用していく形にしましょう。

2024-11-08 10:37 UTC, shtk0llq commented on .eslintrc.json
> +"no-console": "off",
> 取得データの確認がしたかったので、.eslintrc.jsonのno-consoleをoffにしました。

こちらの記述は元に戻しておいていただくようにお願いします。

2024-11-08 10:37 UTC, shtk0llq commented on components/ArticleList/index.tsx
> +  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/blog`);
`NEXT_PUBLIC_API_URL` こちらの環境変数名ですが、ミネギシさんと違うためどちらにするかはお二人で話して君てください。

2024-11-08 12:39 UTC, keita7777 commented on components/ArticleList/index.tsx
> +  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/blog`);
環境変数名は「NEXT_PUBLIC_BASE_URL」で統一させる方向でお願いいたします。
お手数ですが「NEXT_PUBLIC_API_URL」を「NEXT_PUBLIC_BASE_URL」に修正してください。

↓.env.localの記述例
```
NEXT_PUBLIC_BASE_URL="http://localhost:3000"

NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
```

2024-11-08 14:59 UTC, keita7777 requested changes
console.logだけ気になったのでこちらだけ削除お願いします
また[BE]ブログ記事作成機能 #49 をmergeしたことによってコンフリクトが発生してしまいましたので、こちらの解消もお願いします。

2024-11-08 14:59 UTC, keita7777 commented on components/ArticleCard/index.tsx
> +  console.log(data);
データ確認用のconsole.logはmainブランチへ反映するべきでないと思うので削除（`npm run lint`でエラーになる）

2024-11-08 23:03 UTC, yoshida0522 commented
コンフリクト解消しました

2024-11-09 04:51 UTC, keita7777 approved these changes

2024-11-09 04:53 UTC, merged